#!/usr/bin/env bash
# Passwordless systemctl for allowlisted services (Qadbak admin phase 4).
set -euo pipefail

QADBAK_DIR="${QADBAK_DIR:-/opt/qadbak}"
QADBAK_USER="${QADBAK_USER:-qadbak}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root: sudo bash scripts/configure-host-services-sudo.sh" >&2
  exit 1
fi

HELPER="$(readlink -f "$QADBAK_DIR/scripts/host-services-helper.mjs")"
WRAPPER="$(readlink -f "$QADBAK_DIR/scripts/run-host-services-helper.sh")"
if [[ ! -f "$HELPER" ]]; then
  echo "Missing $HELPER — git pull in $QADBAK_DIR first." >&2
  exit 1
fi

NODE_BIN="$(sudo -u "$QADBAK_USER" -H bash -lc 'command -v node' 2>/dev/null | head -1)"
if [[ -z "$NODE_BIN" || ! -x "$NODE_BIN" ]]; then
  NODE_BIN="$(command -v node)"
fi
NODE_BIN="$(readlink -f "$NODE_BIN")"

chmod 755 "$HELPER"
cat >"$WRAPPER" <<EOF
#!/bin/bash
# Generated by configure-host-services-sudo.sh
set -euo pipefail
exec '$NODE_BIN' '$HELPER' "\$@"
EOF
chmod 755 "$WRAPPER"

SUDOERS="/etc/sudoers.d/qadbak-host-services"
cat >"$SUDOERS" <<EOF
# Qadbak admin service control (nginx, postfix, …)
$QADBAK_USER ALL=(root) NOPASSWD: $WRAPPER *
EOF
chmod 440 "$SUDOERS"
visudo -cf "$SUDOERS"

echo "==> Verify host services helper"
if ! sudo -u "$QADBAK_USER" sudo -n "$WRAPPER" list 2>/dev/null | grep -q '"ok"'; then
  echo "FAILED: sudo rule not active." >&2
  exit 1
fi
echo "OK — wrapper: $WRAPPER"
